# nginx
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescale-bridge
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timescale-bridge
  template:
    metadata:
      labels:
        app: timescale-bridge
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'webapp'
        vault.hashicorp.com/auth-path: 'auth/kubernetes-rriv'
        vault.hashicorp.com/agent-inject-secret-credentials.txt: 'secret/data/dev-timescale-creds'
        vault.hashicorp.com/agent-inject-template-credentials: |
          {{- with secret "secret/data/dev-timescale-creds" }}
          export TIMESCALE_DATABASE_PASSWORD={{ .Data.data.password }}
          {{- end }}
    spec:
      serviceAccountName: internal-app
      containers:
      - name: nginx
        image: node
        command: ["/bin/sh", "-c"]
        args:
          - |
            timeout=20
            elapsed=0
            while [ ! -f /vault/secrets/credentials ]; do
              if [ $elapsed -ge $timeout ]; then
                echo "Timeout waiting for Vault to inject secrets"
                exit 1
              fi
              echo "Waiting for Vault to inject secrets..."
              sleep 2
              elapsed=$((elapsed + 2))
            done
            echo "Vault secrets injected"
            . /vault/secrets/credentials
            echo "Starting the application..."
            npm install -g express
            npm install -g pg
            cd `npm root -g`
            pwd
            node <<EOF

              function insert(body){

                const { time, deviceInfo: { devEui }, data } = body;

                console.log('time', time, 'devEui', devEui, 'data', data);

                const dataDecoded = Buffer.from(data, 'base64');
                console.log('dataDecoded', dataDecoded);

                let values = {};

                // decode from naive codec
                const timestamp = dataDecoded.readBigUInt64BE(0);

                class BigIntWrapper {
                  constructor(value) {
                    this.value = value;
                  }
                  toJSON() {
                    return this.value.toString() + 'n';
                  }
                }

                values['timestamp'] = new BigIntWrapper(timestamp);
                console.log(timestamp);
                let j = 1;
                for( i = 8; i < 20; i = i + 4) {
                  const value = dataDecoded.readInt32BE(i) / 100;
                  values['value_'+j] = value;
                  j = j + 1;
                }
                
                const json = JSON.stringify(values);

                const pg = require('pg');

                console.log(process.env);
                const client = new pg.Client({
                  user: 'tsdbadmin',
                  host: 'lwevgo6wge.cd63s5urs1.tsdb.cloud.timescale.com',
                  database: 'tsdb',
                  password: process.env.TIMESCALE_DATABASE_PASSWORD,
                  port: 37881,
                  ssl: true,
                });

                const sql = "INSERT INTO events (time, eui, data, values ) VALUES ( '" +
                  time + 
                  "', '" + 
                  devEui + 
                  "', '" +
                  data + 
                  "', '" +
                  json + 
                  "')";
                console.log('sql:', sql);

                return client.connect()
                  .then(() => {
                    return client.query(sql);
                  })
                  .then(res => {
                    console.log('res:', res);
                    return client.end();
                  })
                  .catch(e => {
                    console.error(e);
                    throw e;
                  });

              }

              const express = require('express');
              const app = express();
              app.use(express.json());
              app.use(express.urlencoded({ extended: true }));

              // Define a route for the root URL
              app.get('/', (req, res) => {
                  res.send('Hi from RRIV!');
              });

              app.post('/rriv-web-hook', (req, res) => {
                console.log('body', req.body);
                insert(req.body)
                  .then(() => {
                    res.send('ok');
                  })
                  .catch(e => {
                    console.error(e);
                    res.status(500).send('error');
                  });
              });

              // Start the server
              app.listen(80, () => {
                  console.log('running...');
              });
            EOF
        ports:
        - containerPort: 80  # NGINX listens on port 80

---
# nodeport service
apiVersion: v1
kind: Service
metadata:
  name: timescale-bridge-service
  namespace: default
spec:
  selector:
    app: timescale-bridge
  ports:
    - port: 30001          # The port that the service will expose
      targetPort: 80    # The port on the container
      nodePort: 30001    # Optional: specify a NodePort (between 30000-32767)
  type: NodePort
      #  ports:
      #    - protocol: TCP
      #      port: 30001           # The port on which the service will be exposed
      #      targetPort: 80      
      #  type: ClusterIP           # Exposes the service only within the cluster (default behavior)

